name: Parser_repos CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t inksne/parser-repos-back-image:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push inksne/parser-repos-back-image:latest

  test:
    runs-on: ubuntu-latest
    needs: build  
    

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pull Docker image from DockerHub
        run: |
          docker pull inksne/parser-repos-back-image:latest

      - name: Run tests
        run: docker run -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} --rm inksne/parser-repos-back-image pytest -v -s

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test  

  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Compose
  #       run: |
  #         docker-compose up -d