name: Parser_repos CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t inksne/parser-repos-back-image:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push inksne/parser-repos-back-image:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pull Docker image from DockerHub
        run: |
          docker pull inksne/parser-repos-back-image:latest

      - name: Wait for PostgreSQL to be ready
        run: |
          docker run --network host --rm jbergknoff/postgresql-client \
            -h localhost -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} \
            -c "SELECT 1;" || exit 1

      - name: Run tests
        run: docker run -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} --rm inksne/parser-repos-back-image pytest -v -s

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test  

  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Compose
  #       run: |
  #         docker-compose up -d
